apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: was
  namespace: argocd
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # Adding tags to subnets for auto-discovery(instead of alb.ingress.kubernetes.io/subnets annotation)
    # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.8/examples/echo_server/
    # Node가 있는 서브넷으로 지정되게 해야한다.
    alb.ingress.kubernetes.io/subnets: subnet-03cf05e420e53fbba, subnet-081da47cceb6ce899
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
    alb.ingress.kubernetes.io/load-balancer-name: skylo-alb
    alb.ingress.kubernetes.io/group.name: skylo
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: echoserver
                port:
                  number: 80
          - path: /user
            pathType: Exact
            backend:
              service:
                name: echoserver
                port:
                  number: 80
